name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      
      - name: 'Use Node 14'
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'

      - name: 'Build and Publish'
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm set "@3PLogic:registry=https://npm.pkg.github.com/"
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"
          yarn install
          yarn build
          npm publish
